"""
Django settings for EventorServer project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$7(hyca3zudksf^oto^xv=q&oa-k4-+n5qlqv7q=!b!838nq&f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['185.81.99.145', '127.0.0.1']
BACKTORY_API_SERVICE_PREFIX = 'http://api.backtory.com'
BACKTORY_STORAGE_SERVICE_PREFIX = 'https://storage.backtory.com'
BACKTORY_STORAGE_ID = '5b165322e4b02c9079767224'
backtory_master_access_token = '9eaf7d24d0014e6286883c7a'
X_BACKTORY_AUTHENTICATION_ID = '5b0ab091e4b0988b2ce05a86'
X_BACKTORY_AUTHENTICATION_KEY = '5b0ab091e4b0322942dd0602'
BACKTORY_REFRESH_TOKEN = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWIxODUyN2FlNGIwOWM4NGI1NTBmZWUzIiwiaXNfZ3Vlc3QiOmZhbHNlLCJ1c2VyX25hbWUiOiI1YjBhYjA5MWU0YjA5ODhiMmNlMDVhODYlJSVtbXNoZXliYW5pIiwic2NvcGUiOlsiY2xpZW50Il0sImF0aSI6IjViZTY2OWNhLTBkMTItNGIxNy1iM2Y0LTg2NzZmYzMzNTk1ZSIsImV4cCI6MjUyODMyMjk1MywianRpIjoiNzBlYmM4MTMtZWEyNy00N2E0LWEwZWMtMzczMzNhYjc2M2Y3IiwiY2xpZW50X2lkIjoiNWIwYWIwOTFlNGIwOTg4YjJjZTA1YTg2In0.uMDt4kYahBo9WMlPFcHGBEnK-tzV9Vca_wQkYzIATs95eDp451WaqKo8gDHQ6fTOGpjPiwNEWLoMddUvsaAyOemZ0GDE4U46YM1Ee_Rau7WzqTutE3M2HzsBYev1G_9xX49JtaeNyvftt5QjyS16VRxlDu2H-ABKuSpd9tgBKfb15uqfyzyiaKu6mCDUSaJHpJJ9s1HGr5giVrrGlSmBhIGAeJhCEqMaJZdVJO3Rlpgbfia1T1kleosjaKVImwK410Onzgf9OisoiaRb09oR0jdXFDGHqaakAR0RpU-ub9-k9K-44XRoGcVc0E3oTNGKicroXOblQQMSmN5Iy5LocQ'
MEDIA_ROOT = os.environ.get('EVENTOR_MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# Application definition
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIAL = True

AUTH_USER_MODEL = 'myuser.User'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myevent.apps.MyeventConfig',
    'myuser.apps.MyuserConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

ROOT_URLCONF = 'EventorServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'myevent/template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EventorServer.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser'
        #...
    )
}
